<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite name="NotableAssessment.app.tests.AppointmentCreationTestCase-20221021001006" tests="1" file="NotableAssessment/app/tests.py" time="0.005" timestamp="2022-10-21T00:10:06" failures="0" errors="0" skipped="0">
		<testcase classname="NotableAssessment.app.tests.AppointmentCreationTestCase" name="test_create_appointment" time="0.005" timestamp="2022-10-21T00:10:06" file="app/tests.py" line="28">
			<system-err><![CDATA[/Users/laithabdel/Documents/GitHub/NotableAssessment/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1564: RuntimeWarning: DateTimeField Appointment.appointment_datetime received a naive datetime (2022-10-21 00:10:06.135035) while time zone support is active.
  warnings.warn(
]]></system-err>
		</testcase>
	</testsuite>
	<testsuite name="NotableAssessment.app.tests.CalendarServiceTestCase-20221021001006" tests="5" file="NotableAssessment/app/tests.py" time="0.020" timestamp="2022-10-21T00:10:06" failures="0" errors="0" skipped="0">
		<testcase classname="NotableAssessment.app.tests.CalendarServiceTestCase" name="test_add_new_appointment_not_15_min_interval" time="0.001" timestamp="2022-10-21T00:10:06" file="app/tests.py" line="139">
			<system-out><![CDATA[19
]]></system-out>
		</testcase>
		<testcase classname="NotableAssessment.app.tests.CalendarServiceTestCase" name="test_add_new_appointment_success" time="0.006" timestamp="2022-10-21T00:10:06" file="app/tests.py" line="92">
			<system-out><![CDATA[0
]]></system-out>
		</testcase>
		<testcase classname="NotableAssessment.app.tests.CalendarServiceTestCase" name="test_add_new_appointment_too_many_appointments" time="0.005" timestamp="2022-10-21T00:10:06" file="app/tests.py" line="114">
			<system-out><![CDATA[0
]]></system-out>
		</testcase>
		<testcase classname="NotableAssessment.app.tests.CalendarServiceTestCase" name="test_delete_appointments" time="0.004" timestamp="2022-10-21T00:10:06" file="app/tests.py" line="74"/>
		<testcase classname="NotableAssessment.app.tests.CalendarServiceTestCase" name="test_get_appointments" time="0.004" timestamp="2022-10-21T00:10:06" file="app/tests.py" line="59">
			<system-err><![CDATA[/Users/laithabdel/Documents/GitHub/NotableAssessment/venv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1564: RuntimeWarning: DateTimeField Appointment.appointment_datetime received a naive datetime (2022-10-01 00:00:00) while time zone support is active.
  warnings.warn(
]]></system-err>
		</testcase>
	</testsuite>
	<testsuite name="NotableAssessment.app.tests.DoctorCreationTestCase-20221021001006" tests="1" file="NotableAssessment/app/tests.py" time="0.002" timestamp="2022-10-21T00:10:06" failures="0" errors="0" skipped="0">
		<testcase classname="NotableAssessment.app.tests.DoctorCreationTestCase" name="test_create_doctor" time="0.002" timestamp="2022-10-21T00:10:06" file="app/tests.py" line="12"/>
	</testsuite>
	<testsuite name="NotableAssessment.app.tests.DoctorServiceTestCase-20221021001006" tests="1" file="NotableAssessment/app/tests.py" time="0.002" timestamp="2022-10-21T00:10:06" failures="0" errors="0" skipped="0">
		<testcase classname="NotableAssessment.app.tests.DoctorServiceTestCase" name="test_get_doctors" time="0.002" timestamp="2022-10-21T00:10:06" file="app/tests.py" line="44"/>
	</testsuite>
	<testsuite name="NotableAssessment.app.tests.PatientCreationTestCase-20221021001006" tests="1" file="NotableAssessment/app/tests.py" time="0.001" timestamp="2022-10-21T00:10:06" failures="0" errors="0" skipped="0">
		<testcase classname="NotableAssessment.app.tests.PatientCreationTestCase" name="test_create_patient" time="0.001" timestamp="2022-10-21T00:10:06" file="app/tests.py" line="20"/>
	</testsuite>
	<testsuite name="NotableAssessment.app.tests.ViewsTestCase-20221021001006" tests="4" file="NotableAssessment/app/tests.py" time="0.030" timestamp="2022-10-21T00:10:06" failures="0" errors="0" skipped="0">
		<testcase classname="NotableAssessment.app.tests.ViewsTestCase" name="test_add_new_appointment" time="0.017" timestamp="2022-10-21T00:10:06" file="app/tests.py" line="195"/>
		<testcase classname="NotableAssessment.app.tests.ViewsTestCase" name="test_delete_appointment" time="0.004" timestamp="2022-10-21T00:10:06" file="app/tests.py" line="189"/>
		<testcase classname="NotableAssessment.app.tests.ViewsTestCase" name="test_get_appointments" time="0.005" timestamp="2022-10-21T00:10:06" file="app/tests.py" line="181"/>
		<testcase classname="NotableAssessment.app.tests.ViewsTestCase" name="test_get_doctors" time="0.004" timestamp="2022-10-21T00:10:06" file="app/tests.py" line="174"/>
	</testsuite>
</testsuites>
